

create table if not exists public.jira_prepared_conversations (
    issue_key text primary key,
    payload jsonb not null,
    merge_context_size_tokens integer,
    dataset_version text not null default 'v1',
    prepared_at timestamptz not null default timezone('utc', now()),
    processed boolean not null default false
);

alter table if exists public.jira_prepared_conversations
    add column if not exists processed boolean not null default false;

create index if not exists idx_jira_prepared_created
    on public.jira_prepared_conversations ((payload ->> 'created'));
create index if not exists idx_jira_prepared_processed
    on public.jira_prepared_conversations (processed, prepared_at);

create table if not exists public.jira_processed_conversations (
    issue_key text primary key,
    status text,
    resolution text,
    rental_id text,
    bike_qr_code text,
    bike_qr_mismatch text,
    custom_field_hub text,
    conversation_start timestamptz,
    conversation_end timestamptz,
    duration_minutes double precision,
    duration_to_resolution double precision,
    first_agent_response_minutes double precision,
    avg_agent_response_minutes double precision,
    avg_customer_response_minutes double precision,
    messages_total integer,
    messages_agent integer,
    messages_customer integer,
    turns integer,
    agent_authors text,
    customer_authors text,
    initial_response_sla_5m boolean,
    initial_response_sla_15m boolean,
    agent_profanity_detected boolean,
    agent_profanity_count integer,
    customer_abuse_detected boolean,
    customer_abuse_count integer,
    llm_summary_250 text,
    conversation_rating text,
    problem_extract text,
    resolution_extract text,
    steps_extract jsonb,
    resolution_timestamp_iso timestamptz,
    resolution_message_index integer,
    contact_reason text,
    contact_reason_original text,
    contact_reason_change boolean,
    reason_override_why text,
    resolution_why text,
    customer_sentiment_primary text,
    customer_sentiment_scores jsonb,
    agent_score double precision,
    customer_score double precision,
    resolved boolean,
    is_resolved boolean,
    improvement_tip text,
    llm_model text,
    llm_input_tokens integer,
    llm_output_tokens integer,
    llm_cost_usd double precision,
    processed_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.misclassification_reviews (
    id bigint generated by default as identity primary key,
    issue_key text not null references public.jira_processed_conversations(issue_key) on delete cascade,
    verdict text not null check (verdict in ('up', 'down')),
    notes text,
    user_id text not null,
    user_display text,
    user_fingerprint text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint misclassification_reviews_issue_user_unique unique (issue_key, user_id)
);

create index if not exists idx_misclassification_reviews_issue on public.misclassification_reviews (issue_key);
create index if not exists idx_misclassification_reviews_user on public.misclassification_reviews (user_id);

-- Project-level configurable prompts and lookups
create table if not exists public.project_config (
    id uuid primary key default gen_random_uuid(),
    type text not null,
    payload jsonb not null,
    version integer not null default 1,
    checksum text,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    updated_by text,
    constraint project_config_type_unique unique (type)
);

create unique index if not exists idx_project_config_type_active on public.project_config (type) where is_active;
create index if not exists idx_project_config_updated_at on public.project_config (updated_at desc);

-- History snapshots for project_config (retain previous versions)
create table if not exists public.project_config_history (
    id uuid primary key default gen_random_uuid(),
    project_config_id uuid,
    type text not null,
    payload jsonb not null,
    version integer not null,
    checksum text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_by text
);
create index if not exists idx_project_config_history_type on public.project_config_history (type);
create index if not exists idx_project_config_history_created_at on public.project_config_history (created_at desc);

create table if not exists public.contact_taxonomy_versions (
    id uuid primary key default gen_random_uuid(),
    version integer not null default 1,
    notes text,
    status text not null default 'NEW' check (status in ('NEW', 'IN_USE', 'OBSOLETED', 'CANCELLED')),
    created_at timestamptz not null default timezone('utc', now()),
    created_by text
);

create unique index if not exists idx_contact_taxonomy_in_use on public.contact_taxonomy_versions (status) where status = 'IN_USE';
create index if not exists idx_contact_taxonomy_version on public.contact_taxonomy_versions (version desc);
create index if not exists idx_contact_taxonomy_created_at on public.contact_taxonomy_versions (created_at desc);

-- Individual contact taxonomy reasons (one row per topic/sub-reason)
create table if not exists public.contact_taxonomy_reasons (
    id uuid primary key default gen_random_uuid(),
    version_id uuid not null references public.contact_taxonomy_versions(id) on delete cascade,
    topic text not null,
    sub_reason text,
    description text,
    keywords text[],
    sort_order integer not null default 0,
    status text not null default 'IN_USE' check (status in ('NEW', 'IN_USE', 'OBSOLETED', 'CANCELLED')),
    created_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.contact_taxonomy_reasons
    add column if not exists status text not null default 'IN_USE' check (status in ('NEW', 'IN_USE', 'OBSOLETED', 'CANCELLED'));

create index if not exists idx_contact_taxonomy_reasons_version on public.contact_taxonomy_reasons (version_id);
create index if not exists idx_contact_taxonomy_reasons_order on public.contact_taxonomy_reasons (version_id, sort_order);
create index if not exists idx_contact_taxonomy_reasons_status on public.contact_taxonomy_reasons (status);
create unique index if not exists idx_contact_taxonomy_reason_unique on public.contact_taxonomy_reasons (version_id, topic, coalesce(sub_reason, ''));

-- Cleanup legacy column if present
alter table if exists public.contact_taxonomy_versions drop column if exists labels;
