"""
Default contact taxonomy definitions used as a fallback when Supabase is unavailable.
"""

from __future__ import annotations

from typing import Dict, Tuple

AGENT_CONTACT_HEADINGS: Tuple[str, ...] = (
    "System outage",
    "Request to transfer subscription/pass to a different hub",
    "info/question about my current subscription / pass",
    "Hub access or navigation issue",
    "E-bike availability issue",
    "E-bike damage issue",
    "Payment method change/edit",
    "Other",
    "Duplicate",
    "Customer Feedback",
    "My account is blocked",
    "General information request about the service",
    "Rental finish issue",
    "Request to cancel weekly subscription",
    "Issue unknown",
    "E-bike lost or stolen during a rental",
    "Info/question about my current ride",
    "Refund request",
    "Change personal information",
    "Request to cancel daily pass",
    "Can't access rentals after payment",
    "(B2B) Rental start issue",
    "Rental start issue",
    "Payment issues",
    "Dock availability issue",
    "Hub sold out",
    "General complaint",
    "Rental pause/resume issue",
    "Info about advanced booking",
    "Delete account",
    "Invoice or receipt request",
    "Promotions or discounts question / issue",
    "Login / signup issue",
    "Info about monthly subscription",
    "Answer from customer to Port outbound contact",
)

DEFAULT_CONTACT_REASON = "Other"

KEYWORD_CONTACT_MAP: Dict[str, Tuple[str, ...]] = {
    "System outage": (
        "system outage",
        "network outage",
        "not working",
        "offline",
        "all docks red",
    ),
    "Request to transfer subscription/pass to a different hub": (
        "transfer subscription",
        "transfer pass",
        "move subscription",
        "change hub",
    ),
    "info/question about my current subscription / pass": (
        "subscription info",
        "subscription question",
        "pass info",
        "pass question",
        "subscription status",
    ),
    "Hub access or navigation issue": (
        "can't find hub",
        "navigation issue",
        "where is the hub",
        "hub access",
        "directions to hub",
    ),
    "E-bike availability issue": (
        "no bikes available",
        "bike unavailable",
        "no ebike",
        "availability issue",
        "bikes all taken",
    ),
    "E-bike damage issue": (
        "wheel broken",
        "no air",
        "flat tire",
        "handlebar issue",
        "hard to pedal",
    ),
    "Payment method change/edit": (
        "change payment",
        "update payment",
        "edit payment",
        "new card",
        "payment method",
    ),
    "Duplicate": ("duplicate ticket", "duplicate issue", "already submitted"),
    "Customer Feedback": ("feedback", "suggestion", "compliment", "complaint"),
    "My account is blocked": ("account blocked", "account locked", "locked out"),
    "General information request about the service": (
        "general info",
        "information about service",
        "service question",
    ),
    "Rental finish issue": (
        "finish rental",
        "end ride",
        "complete rental",
        "close rental",
        "bike won't end",
    ),
    "Request to cancel weekly subscription": (
        "cancel weekly",
        "stop weekly",
        "weekly subscription cancel",
    ),
    "Issue unknown": ("issue unknown", "not sure the issue", "unclear issue"),
    "E-bike lost or stolen during a rental": (
        "bike lost",
        "bike stolen",
        "lost during rental",
        "stolen during rental",
    ),
    "Info/question about my current ride": (
        "current ride",
        "ride info",
        "ride question",
        "trip question",
    ),
    "Refund request": ("refund", "money back", "chargeback", "request a refund"),
    "Change personal information": (
        "change personal",
        "update personal",
        "change email",
        "change phone",
        "update details",
    ),
    "Request to cancel daily pass": (
        "cancel daily",
        "stop daily pass",
        "daily pass cancel",
    ),
    "Can't access rentals after payment": (
        "can't access rentals",
        "cannot access rentals",
        "can't rent after payment",
        "payment went through but",
    ),
    "(B2B) Rental start issue": (
        "b2b rental",
        "business rental",
        "corporate rental",
        "b2b start",
    ),
    "Rental start issue": (
        "start rental",
        "begin rental",
        "start ride",
        "rental won't start",
        "start issue",
    ),
    "Payment issues": (
        "payment issue",
        "payment problem",
        "payment failed",
        "double charged",
        "charged twice",
        "billing issue",
        "payment declined",
    ),
    "Dock availability issue": (
        "no docks available",
        "dock full",
        "no empty dock",
        "return dock issue",
        "dock unavailable",
    ),
    "Hub sold out": (
        "hub sold out",
        "sold out hub",
        "hub empty",
        "no bikes at hub",
        "hub has no bikes",
    ),
    "General complaint": (
        "complaint",
        "not satisfied",
        "unhappy with service",
        "bad experience",
        "poor service",
    ),
    "Rental pause/resume issue": (
        "bike won't resume",
        "bike doesn't unlock",
        "app doesn't unlock",
    ),
    "Info about advanced booking": (
        "advanced booking",
        "prebook",
        "book bike",
        "reserve bike",
    ),
    "Delete account": ("delete account", "remove account", "close account"),
    "Invoice or receipt request": ("invoice", "receipt", "tax receipt", "proof of payment"),
    "Promotions or discounts question / issue": ("promo", "discount", "coupon", "code not working"),
    "Login / signup issue": ("login", "signup", "sign up", "cannot log in"),
    "Info about monthly subscription": ("monthly subscription", "monthly pass", "monthly plan"),
    "Answer from customer to Port outbound contact": ("reply to port", "response to port message"),
}
